### ISSUE TITLE
LNK2019: unresolved external symbol Scintilla_RegisterClasses in wWinMain 

### ISSUE THREAD

**Issue by EthanZBY** [zodiacon/TotalPE2#1]
After adding the missing folder TotalPE2\scintilla\win32 from the downloaded scintilla source, LNK2019 error occurred.

**Comment by EthanZBY** [comment]
win32 folder in scintilla is not pushed into git repository, can you please add it?

https://scintilla-interest.narkive.com/XUpyrWbT/compiling-and-using-scintilla-as-static-library-in-my-app

"On Windows, Scintilla is normally used as a dynamic
library as a .DLL file. If you want to link Scintilla
directly into your application .EXE or .DLL file, then
the STATIC_BUILD preprocessor symbol should be defined
and Scintilla_RegisterClasses called. STATIC_BUILD
prevents compiling the DllMain function which will
conflict with any DllMain defined in your code.
Scintilla_RegisterClasses takes the HINSTANCE of your
application and ensures that the "Scintilla" window
class is registered. To make sure that the right
pointing arrow cursor used in the margin is displayed
by Scintilla add the scintilla/win32/Margin.cur file
to your application's resources with the ID IDC_MARGIN
which is defined in scintilla/win32/platfromRes.h as
400."

I guess the original win32 folder vcporject setting is not for STATIC_BUILD...

**Comment by EthanZBY** [comment]
> Which externals are missing?

win32 folder in scintilla is not pushed into git repository, can you please add it?

https://scintilla-interest.narkive.com/XUpyrWbT/compiling-and-using-scintilla-as-static-library-in-my-app

"On Windows, Scintilla is normally used as a dynamic
library as a .DLL file. If you want to link Scintilla
directly into your application .EXE or .DLL file, then
the STATIC_BUILD preprocessor symbol should be defined
and Scintilla_RegisterClasses called. STATIC_BUILD
prevents compiling the DllMain function which will
conflict with any DllMain defined in your code.
Scintilla_RegisterClasses takes the HINSTANCE of your
application and ensures that the "Scintilla" window
class is registered. To make sure that the right
pointing arrow cursor used in the margin is displayed
by Scintilla add the scintilla/win32/Margin.cur file
to your application's resources with the ID IDC_MARGIN
which is defined in scintilla/win32/platfromRes.h as
400."

I guess the original win32 folder vcporject setting is not for STATIC_BUILD...

**Comment by zodiacon** [comment]
Done.
It seems a rule in .gitignore rejected "Win32"...
